dbt_test:
  target: docker
  outputs:
    docker:
      type: postgres
      host: "{{ env_var('DB_URL') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DB_DB') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
      threads: 4