name: pre-commit

on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

    #   - name: Set up Python
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: '3.11'

    # #   - name: Install dependencies
    # #     run: |
    # #       python -m pip install --upgrade pip
    # #       pip install pre-commit dbt-core dbt-postgres

    # #   - name: Run pre-commit hooks
    # #     run: pre-commit run --all-files
      - name: Load environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DB=${{ secrets.DB_DB }}" >> $GITHUB_ENV
          echo "DB_SCHEMA=${{ secrets.DB_SCHEMA }}" >> $GITHUB_ENV

      - name: Run pre-commit hooks
        uses: dbt-checkpoint/action@v0.1
        with:
            extra_args: --all-files
            dbt_version: 1.6.3
            dbt_adapter: dbt-postgres
        env:
          DB_URL: ${{ env.DB_URL }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_DB: ${{ env.DB_DB }}
          DB_SCHEMA: ${{ env.DB_SCHEMA }}