name: pre-commit

on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install pre-commit dbt-core dbt-postgres

    #   - name: Run pre-commit hooks
    #     run: pre-commit run --all-files

      - name: Run pre-commit hooks
        uses: dbt-checkpoint/action@v0.1
        with:
            extra_args: --all-files
            dbt_version: 1.6.3
            dbt_adapter: dbt-postgres